//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Specs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exceptions
    {
        public System.Guid ExceptionID { get; set; }
        public string LUCExceptionType { get; set; }
        public string PolicyNo { get; set; }
        public string GovID { get; set; }
        public string AccountNumber { get; set; }
        public string FirstNames { get; set; }
        public string SurName { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public string DeletedByName { get; set; }
        public System.Guid GenisysID { get; set; }
    }
}
