//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Specs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalEntity
    {
        public GlobalEntity()
        {
            this.MerchCode = new HashSet<MerchCode>();
            this.Office = new HashSet<Office>();
            this.Office1 = new HashSet<Office>();
        }
    
        public System.Guid GlobalEntityID { get; set; }
        public string FirstNames { get; set; }
        public string Surname { get; set; }
        public string PreferredName { get; set; }
        public string GovID { get; set; }
        public string Passport { get; set; }
        public string CountryID { get; set; }
        public string LUCPreferredLanguage { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string LUCMaritalStatus { get; set; }
        public string LUCEntityStatus { get; set; }
        public string EmployerName { get; set; }
        public string EmployeeNo { get; set; }
        public string LUCIncomeCategory { get; set; }
        public Nullable<int> SalaryPayDay { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> LastEntityLogin { get; set; }
        public int TrackingNumber { get; set; }
        public Nullable<int> LegacyMemberID { get; set; }
        public Nullable<int> LegacyUserID { get; set; }
        public Nullable<int> LegacyMerchID { get; set; }
        public Nullable<System.Guid> FileRef { get; set; }
        public string LUCFicaStatus { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<int> LoginAttemptCounter { get; set; }
        public Nullable<bool> IsStaff { get; set; }
        public string CompanyRegNo { get; set; }
        public string VatRegNo { get; set; }
        public string LUCGovIDStatus { get; set; }
        public Nullable<System.DateTime> IDVerificationDate { get; set; }
        public string LUCIDVerificationSource { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public string LastUsedPassword { get; set; }
        public string LUCTitle { get; set; }
        public string LUCEthnicity { get; set; }
        public Nullable<bool> IsNetworkLogin { get; set; }
    
        public virtual ICollection<MerchCode> MerchCode { get; set; }
        public virtual ICollection<Office> Office { get; set; }
        public virtual ICollection<Office> Office1 { get; set; }
    }
}
