//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Specs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchCode
    {
        public string OfficeCode { get; set; }
        public string MerchCode1 { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.Guid GlobalEntityID { get; set; }
        public System.Guid MerchLevelID { get; set; }
        public string LUCMerchStatus { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public Nullable<decimal> SavingsBalance { get; set; }
        public Nullable<int> LegacyMerchLevelID { get; set; }
        public Nullable<int> LegacyMerchandiserCodeID { get; set; }
        public Nullable<int> LegacyMerchID { get; set; }
        public Nullable<bool> Latest { get; set; }
        public System.Guid GenisysID { get; set; }
        public string AwaitingSponsorCode { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> InvestmentSlushFund { get; set; }
        public Nullable<decimal> OwnerSlushFund { get; set; }
        public Nullable<bool> isPIP { get; set; }
        public byte CODLevel { get; set; }
        public Nullable<decimal> InvestmentFund { get; set; }
        public Nullable<decimal> OwnerFund { get; set; }
        public string LUCHighestQualification { get; set; }
        public Nullable<decimal> EventFundBalance { get; set; }
        public Nullable<decimal> RallyFundBalance { get; set; }
    }
}
