//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Specs.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.BouquetOffice = new HashSet<BouquetOffice>();
        }
    
        public string OfficeCode { get; set; }
        public System.Guid GlobalEntityID { get; set; }
        public System.Guid LocationID { get; set; }
        public Nullable<System.Guid> OwnerEntityID { get; set; }
        public string OfficeName { get; set; }
        public bool PaysOverheads { get; set; }
        public Nullable<decimal> CurrentSuccessRate { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<System.Guid> InsertedBy { get; set; }
        public string InsertedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public string LUCOfficeStatus { get; set; }
        public System.Guid GenisysID { get; set; }
        public bool isNewOffice { get; set; }
        public Nullable<decimal> OfficeWeighting { get; set; }
        public string ParentSalesChannelID { get; set; }
        public string SalesChannelID { get; set; }
    
        public virtual ICollection<BouquetOffice> BouquetOffice { get; set; }
        public virtual GlobalEntity GlobalEntity { get; set; }
        public virtual GlobalEntity GlobalEntity1 { get; set; }
    }
}
